### ISSUE TITLE
Great job i wish there is a version for android

### ISSUE THREAD

**Issue by innovationnow** [konsumer/tplink-lightbulb#24]
Hi,
Really amazing and great job, simple code and it works, i wish there is version for android, i need it urgently for my project :( 
any way thank you very much for your work, wish u can help me with android

**Comment by konsumer** [comment]
Thanks!

You have a couple options, that this project might still help with:

* If you are using react-native, or something else that uses javascript to make native code, all the code should work other than the actual "send UDP message"
* Port the code to java. The main bit of the whole lib are in `send` and `scan`, and could even be minimized to just `send` with the right way of thinking about it. Most of the API is "send this JSON, encrypt it, over UDP on port 9998, decrypt and return decoded JSON".  `scan` uses port 9999 for broadcast message. 

I'm going to close this issue because it's outside of the scope of "nodejs library for controlling tplink light devices" but I think you could use it as a solid base to write your own.

basic idea if you port it or reuse it should be like this:

* port/copy&paste `encrypt` and `decrypt`, write your own UDP sender
* send a message on `255.255.255.255:9999` that is an encrypted JSON: `{"system":{"get_sysinfo":{}}}` this is a broadacst that will make everyone answer about themselves (scan)
* wait for broadcast answers on `9998`
* Use example messages in this code to get an idea of the format of the JSON for commands, send it on port `9999 `.
