### ISSUE TITLE
Can you build an android version?

### ISSUE THREAD

**Issue by lexterror** [konsumer/tplink-lightbulb#38]
I wanted to know whether you could build an android version.

Thank you.

**Comment by konsumer** [comment]
No, that is outside the scope of this project.

I have found that it's a bit easier on other platforms that have basic HTTP (like microcontrollers and stuff) to use the kasa protocol instead of hitting the bulbs directly with UDP packets. It works over the internet (not just your LAN where the bulbs are located) and would work better overall with android, I think.

If you want to write an android lib, check out [kasa_control](https://github.com/konsumer/kasa_control). It's also written in node, but uses simple HTTP requests, so it should be fairly trivial to port. Implement the [kasa method](https://github.com/konsumer/kasa_control/blob/master/src/lib.js#L36-L47) then all the others should be pretty simple (send JSON, get JSON responses.)

You can use this lib as a reference for message formats (to use in your version of [send](https://github.com/konsumer/kasa_control/blob/master/src/lib.js#L70-L73)) for messages that aren't built in [kasa_control](https://github.com/konsumer/kasa_control).

Your process will probably be similar to this:

* Make a basic request-wrapper like [kasa](https://github.com/konsumer/kasa_control/blob/master/src/lib.js#L36-L47)
* do login with `kasa('login', { appType: 'Kasa_Android', cloudUserName, cloudPassword, terminalUUID: RANDOM_UUID4 })`
* get list of devices with `kasa('getDeviceList')`
* run requests with `kasa('passthrough', {deviceId, requestData: JSON.stringify(msg)})`

You can find example `msg` objects [here](https://github.com/konsumer/tplink-lightbulb/blob/master/src/lib.js).
