### ISSUE TITLE
Invalid exports main target for dist/tplink-lightbulb.modern.js

### ISSUE THREAD

**Issue by spinningmonkey** [konsumer/tplink-lightbulb#63]
Attempted to run this from WSL and PowerShell, seeing this issue on both. Not very familiar with Node so potentially it's an end user error or maybe this module is for specific version of node and pm?

`Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "dist/tplink-lightbulb.modern.js" defined in the package config /mnt/c/Users/username/node_modules/tplink-lightbulb/package.json; targets must start with "./"`

**Comment by spinningmonkey** [comment]
the dist directory is in your .gitignore file so this isn't getting pushed to this repository
https://github.com/konsumer/tplink-lightbulb/blob/main/.gitignore#L4

**Comment by konsumer** [comment]
> the dist directory is in your .gitignore file so this isn't getting pushed to this repository

No. It has always been ignored from git. This is intentional. `dist` is built (before publish) and normally included in npm. It is not included in git (it's bad practice to commit built things to git, for lots of good reasons.)

You can see the problem for yourself:

```
npm v tplink-lightbulb dist.tarball | xargs curl | tar -xz
tree package

package
├── LICENSE
├── package.json
├── README.md
└── src
    └── tplight.cjs
```

None of the source files that should be in there are only tplight.cjs, which is the CLI wrapper).

I was originally fixing the issue of all export statements in package.json (`exports`, `main`, `module`, `unpkg`) all require relative (starts with `./`) paths, now, when they didn't use to. I made `files` match, but I think it needs to not match (not start with `./`) Very annoying.

With the change, I get this message on publish:

```
npm notice 📦  tplink-lightbulb@1.7.7
npm notice === Tarball Contents === 
npm notice 1.1kB  LICENSE                            
npm notice 7.7kB  README.md                          
npm notice 8.0kB  dist/tplink-lightbulb.cjs          
npm notice 15.0kB dist/tplink-lightbulb.cjs.map      
npm notice 7.7kB  dist/tplink-lightbulb.modern.js    
npm notice 15.0kB dist/tplink-lightbulb.modern.js.map
npm notice 7.7kB  dist/tplink-lightbulb.module.js    
npm notice 15.0kB dist/tplink-lightbulb.module.js.map
npm notice 8.9kB  dist/tplink-lightbulb.umd.js       
npm notice 15.0kB dist/tplink-lightbulb.umd.js.map   
npm notice 1.6kB  package.json                       
npm notice 6.4kB  src/index.js                       
npm notice 10.7kB src/tplight.cjs ```

so it should be good in tplink-lightbulb@1.7.7.

**Comment by spinningmonkey** [comment]
Thanks for the quick response and lesson on npm! Seeing built files in dist directory now.
